/* Schema tabella generato automaticamente 
 * 2022-10-03:15:55:28.601922
 * Non modificare */
CREATE TABLE codNazioni (
    City VARCHAR(64) NOT NULL,
    Code VARCHAR(4) NOT NULL PRIMARY KEY
);

INSERT INTO codNazioni(City,Code) VALUES ("Albania","Z100");
INSERT INTO codNazioni(City,Code) VALUES ("Andorra","Z101");
INSERT INTO codNazioni(City,Code) VALUES ("Austria","Z102");
INSERT INTO codNazioni(City,Code) VALUES ("Belgio","Z103");
INSERT INTO codNazioni(City,Code) VALUES ("Bulgaria","Z104");
INSERT INTO codNazioni(City,Code) VALUES ("Danimarca","Z107");
INSERT INTO codNazioni(City,Code) VALUES ("Finlandia","Z109");
INSERT INTO codNazioni(City,Code) VALUES ("Francia","Z110");
INSERT INTO codNazioni(City,Code) VALUES ("Germania","Z112");
INSERT INTO codNazioni(City,Code) VALUES ("Regno Unito","Z114");
INSERT INTO codNazioni(City,Code) VALUES ("Grecia","Z115");
INSERT INTO codNazioni(City,Code) VALUES ("Irlanda","Z116");
INSERT INTO codNazioni(City,Code) VALUES ("Islanda","Z117");
INSERT INTO codNazioni(City,Code) VALUES ("Liechtenstein","Z119");
INSERT INTO codNazioni(City,Code) VALUES ("Lussemburgo","Z120");
INSERT INTO codNazioni(City,Code) VALUES ("Malta","Z121");
INSERT INTO codNazioni(City,Code) VALUES ("Monaco","Z123");
INSERT INTO codNazioni(City,Code) VALUES ("Norvegia","Z125");
INSERT INTO codNazioni(City,Code) VALUES ("Paesi Bassi","Z126");
INSERT INTO codNazioni(City,Code) VALUES ("Polonia","Z127");
INSERT INTO codNazioni(City,Code) VALUES ("Portogallo","Z128");
INSERT INTO codNazioni(City,Code) VALUES ("Romania","Z129");
INSERT INTO codNazioni(City,Code) VALUES ("San Marino","Z130");
INSERT INTO codNazioni(City,Code) VALUES ("Spagna","Z131");
INSERT INTO codNazioni(City,Code) VALUES ("Svezia","Z132");
INSERT INTO codNazioni(City,Code) VALUES ("Svizzera","Z133");
INSERT INTO codNazioni(City,Code) VALUES ("Ucraina","Z138");
INSERT INTO codNazioni(City,Code) VALUES ("Ungheria","Z134");
INSERT INTO codNazioni(City,Code) VALUES ("Federazione russa","Z154");
INSERT INTO codNazioni(City,Code) VALUES ("Stato della Città del Vaticano","Z106");
INSERT INTO codNazioni(City,Code) VALUES ("Estonia","Z144");
INSERT INTO codNazioni(City,Code) VALUES ("Lettonia","Z145");
INSERT INTO codNazioni(City,Code) VALUES ("Lituania","Z146");
INSERT INTO codNazioni(City,Code) VALUES ("Croazia","Z149");
INSERT INTO codNazioni(City,Code) VALUES ("Slovenia","Z150");
INSERT INTO codNazioni(City,Code) VALUES ("Bosnia-Erzegovina","Z153");
INSERT INTO codNazioni(City,Code) VALUES ("Macedonia del Nord","Z148");
INSERT INTO codNazioni(City,Code) VALUES ("Moldova","Z140");
INSERT INTO codNazioni(City,Code) VALUES ("Slovacchia","Z155");
INSERT INTO codNazioni(City,Code) VALUES ("Bielorussia","Z139");
INSERT INTO codNazioni(City,Code) VALUES ("Repubblica ceca","Z156");
INSERT INTO codNazioni(City,Code) VALUES ("Montenegro","Z159");
INSERT INTO codNazioni(City,Code) VALUES ("Serbia","Z158");
INSERT INTO codNazioni(City,Code) VALUES ("Kosovo","Z160");
INSERT INTO codNazioni(City,Code) VALUES ("Afghanistan","Z200");
INSERT INTO codNazioni(City,Code) VALUES ("Arabia Saudita","Z203");
INSERT INTO codNazioni(City,Code) VALUES ("Bahrein","Z204");
INSERT INTO codNazioni(City,Code) VALUES ("Bangladesh","Z249");
INSERT INTO codNazioni(City,Code) VALUES ("Bhutan","Z205");
INSERT INTO codNazioni(City,Code) VALUES ("Myanmar/Birmania","Z206");
INSERT INTO codNazioni(City,Code) VALUES ("Brunei Darussalam","Z207");
INSERT INTO codNazioni(City,Code) VALUES ("Cambogia","Z208");
INSERT INTO codNazioni(City,Code) VALUES ("Sri Lanka","Z209");
INSERT INTO codNazioni(City,Code) VALUES ("Cina","Z210");
INSERT INTO codNazioni(City,Code) VALUES ("Cipro","Z211");
INSERT INTO codNazioni(City,Code) VALUES ("Corea del Nord","Z214");
INSERT INTO codNazioni(City,Code) VALUES ("Corea del Sud","Z213");
INSERT INTO codNazioni(City,Code) VALUES ("Emirati Arabi Uniti","Z215");
INSERT INTO codNazioni(City,Code) VALUES ("Filippine","Z216");
INSERT INTO codNazioni(City,Code) VALUES ("Palestina","Z161");
INSERT INTO codNazioni(City,Code) VALUES ("Giappone","Z219");
INSERT INTO codNazioni(City,Code) VALUES ("Giordania","Z220");
INSERT INTO codNazioni(City,Code) VALUES ("India","Z222");
INSERT INTO codNazioni(City,Code) VALUES ("Indonesia","Z223");
INSERT INTO codNazioni(City,Code) VALUES ("Iran","Z224");
INSERT INTO codNazioni(City,Code) VALUES ("Iraq","Z225");
INSERT INTO codNazioni(City,Code) VALUES ("Israele","Z226");
INSERT INTO codNazioni(City,Code) VALUES ("Kuwait","Z227");
INSERT INTO codNazioni(City,Code) VALUES ("Laos","Z228");
INSERT INTO codNazioni(City,Code) VALUES ("Libano","Z229");
INSERT INTO codNazioni(City,Code) VALUES ("Timor Leste","Z242");
INSERT INTO codNazioni(City,Code) VALUES ("Maldive","Z232");
INSERT INTO codNazioni(City,Code) VALUES ("Malaysia","Z247");
INSERT INTO codNazioni(City,Code) VALUES ("Mongolia","Z233");
INSERT INTO codNazioni(City,Code) VALUES ("Nepal","Z234");
INSERT INTO codNazioni(City,Code) VALUES ("Oman","Z235");
INSERT INTO codNazioni(City,Code) VALUES ("Pakistan","Z236");
INSERT INTO codNazioni(City,Code) VALUES ("Qatar","Z237");
INSERT INTO codNazioni(City,Code) VALUES ("Singapore","Z248");
INSERT INTO codNazioni(City,Code) VALUES ("Siria","Z240");
INSERT INTO codNazioni(City,Code) VALUES ("Thailandia","Z241");
INSERT INTO codNazioni(City,Code) VALUES ("Turchia","Z243");
INSERT INTO codNazioni(City,Code) VALUES ("Vietnam","Z251");
INSERT INTO codNazioni(City,Code) VALUES ("Yemen","Z246");
INSERT INTO codNazioni(City,Code) VALUES ("Kazakhstan","Z255");
INSERT INTO codNazioni(City,Code) VALUES ("Uzbekistan","Z259");
INSERT INTO codNazioni(City,Code) VALUES ("Armenia","Z252");
INSERT INTO codNazioni(City,Code) VALUES ("Azerbaigian","Z253");
INSERT INTO codNazioni(City,Code) VALUES ("Georgia","Z254");
INSERT INTO codNazioni(City,Code) VALUES ("Kirghizistan","Z256");
INSERT INTO codNazioni(City,Code) VALUES ("Tagikistan","Z257");
INSERT INTO codNazioni(City,Code) VALUES ("Taiwan","Z217");
INSERT INTO codNazioni(City,Code) VALUES ("Turkmenistan","Z258");
INSERT INTO codNazioni(City,Code) VALUES ("Algeria","Z301");
INSERT INTO codNazioni(City,Code) VALUES ("Angola","Z302");
INSERT INTO codNazioni(City,Code) VALUES ("Costa d'Avorio","Z313");
INSERT INTO codNazioni(City,Code) VALUES ("Benin","Z314");
INSERT INTO codNazioni(City,Code) VALUES ("Botswana","Z358");
INSERT INTO codNazioni(City,Code) VALUES ("Burkina Faso","Z354");
INSERT INTO codNazioni(City,Code) VALUES ("Burundi","Z305");
INSERT INTO codNazioni(City,Code) VALUES ("Camerun","Z306");
INSERT INTO codNazioni(City,Code) VALUES ("Capo Verde","Z307");
INSERT INTO codNazioni(City,Code) VALUES ("Repubblica Centrafricana","Z308");
INSERT INTO codNazioni(City,Code) VALUES ("Ciad","Z309");
INSERT INTO codNazioni(City,Code) VALUES ("Comore","Z310");
INSERT INTO codNazioni(City,Code) VALUES ("Congo","Z311");
INSERT INTO codNazioni(City,Code) VALUES ("Egitto","Z336");
INSERT INTO codNazioni(City,Code) VALUES ("Etiopia","Z315");
INSERT INTO codNazioni(City,Code) VALUES ("Gabon","Z316");
INSERT INTO codNazioni(City,Code) VALUES ("Gambia","Z317");
INSERT INTO codNazioni(City,Code) VALUES ("Ghana","Z318");
INSERT INTO codNazioni(City,Code) VALUES ("Gibuti","Z361");
INSERT INTO codNazioni(City,Code) VALUES ("Guinea","Z319");
INSERT INTO codNazioni(City,Code) VALUES ("Guinea-Bissau","Z320");
INSERT INTO codNazioni(City,Code) VALUES ("Guinea equatoriale","Z321");
INSERT INTO codNazioni(City,Code) VALUES ("Kenya","Z322");
INSERT INTO codNazioni(City,Code) VALUES ("Lesotho","Z359");
INSERT INTO codNazioni(City,Code) VALUES ("Liberia","Z325");
INSERT INTO codNazioni(City,Code) VALUES ("Libia","Z326");
INSERT INTO codNazioni(City,Code) VALUES ("Madagascar","Z327");
INSERT INTO codNazioni(City,Code) VALUES ("Malawi","Z328");
INSERT INTO codNazioni(City,Code) VALUES ("Mali","Z329");
INSERT INTO codNazioni(City,Code) VALUES ("Marocco","Z330");
INSERT INTO codNazioni(City,Code) VALUES ("Mauritania","Z331");
INSERT INTO codNazioni(City,Code) VALUES ("Maurizio","Z332");
INSERT INTO codNazioni(City,Code) VALUES ("Mozambico","Z333");
INSERT INTO codNazioni(City,Code) VALUES ("Namibia","Z300");
INSERT INTO codNazioni(City,Code) VALUES ("Niger","Z334");
INSERT INTO codNazioni(City,Code) VALUES ("Nigeria","Z335");
INSERT INTO codNazioni(City,Code) VALUES ("Ruanda","Z338");
INSERT INTO codNazioni(City,Code) VALUES ("Sao Tomé e Principe","Z341");
INSERT INTO codNazioni(City,Code) VALUES ("Seychelles","Z342");
INSERT INTO codNazioni(City,Code) VALUES ("Senegal","Z343");
INSERT INTO codNazioni(City,Code) VALUES ("Sierra Leone","Z344");
INSERT INTO codNazioni(City,Code) VALUES ("Somalia","Z345");
INSERT INTO codNazioni(City,Code) VALUES ("Sudafrica","Z347");
INSERT INTO codNazioni(City,Code) VALUES ("Sudan","Z348");
INSERT INTO codNazioni(City,Code) VALUES ("Eswatini","Z349");
INSERT INTO codNazioni(City,Code) VALUES ("Tanzania","Z357");
INSERT INTO codNazioni(City,Code) VALUES ("Togo","Z351");
INSERT INTO codNazioni(City,Code) VALUES ("Tunisia","Z352");
INSERT INTO codNazioni(City,Code) VALUES ("Uganda","Z353");
INSERT INTO codNazioni(City,Code) VALUES ("Repubblica Democratica del Congo","Z312");
INSERT INTO codNazioni(City,Code) VALUES ("Zambia","Z355");
INSERT INTO codNazioni(City,Code) VALUES ("Zimbabwe","Z337");
INSERT INTO codNazioni(City,Code) VALUES ("Eritrea","Z368");
INSERT INTO codNazioni(City,Code) VALUES ("Sud Sudan","Z907");
INSERT INTO codNazioni(City,Code) VALUES ("Antigua e Barbuda","Z532");
INSERT INTO codNazioni(City,Code) VALUES ("Bahamas","Z502");
INSERT INTO codNazioni(City,Code) VALUES ("Barbados","Z522");
INSERT INTO codNazioni(City,Code) VALUES ("Belize","Z512");
INSERT INTO codNazioni(City,Code) VALUES ("Canada","Z401");
INSERT INTO codNazioni(City,Code) VALUES ("Costa Rica","Z503");
INSERT INTO codNazioni(City,Code) VALUES ("Cuba","Z504");
INSERT INTO codNazioni(City,Code) VALUES ("Dominica","Z526");
INSERT INTO codNazioni(City,Code) VALUES ("Repubblica Dominicana","Z505");
INSERT INTO codNazioni(City,Code) VALUES ("El Salvador","Z506");
INSERT INTO codNazioni(City,Code) VALUES ("Giamaica","Z507");
INSERT INTO codNazioni(City,Code) VALUES ("Grenada","Z524");
INSERT INTO codNazioni(City,Code) VALUES ("Guatemala","Z509");
INSERT INTO codNazioni(City,Code) VALUES ("Haiti","Z510");
INSERT INTO codNazioni(City,Code) VALUES ("Honduras","Z511");
INSERT INTO codNazioni(City,Code) VALUES ("Messico","Z514");
INSERT INTO codNazioni(City,Code) VALUES ("Nicaragua","Z515");
INSERT INTO codNazioni(City,Code) VALUES ("Panama","Z516");
INSERT INTO codNazioni(City,Code) VALUES ("Santa Lucia","Z527");
INSERT INTO codNazioni(City,Code) VALUES ("Saint Vincent e Grenadine","Z528");
INSERT INTO codNazioni(City,Code) VALUES ("Saint Kitts e Nevis","Z533");
INSERT INTO codNazioni(City,Code) VALUES ("Stati Uniti d'America","Z404");
INSERT INTO codNazioni(City,Code) VALUES ("Argentina","Z600");
INSERT INTO codNazioni(City,Code) VALUES ("Bolivia","Z601");
INSERT INTO codNazioni(City,Code) VALUES ("Brasile","Z602");
INSERT INTO codNazioni(City,Code) VALUES ("Cile","Z603");
INSERT INTO codNazioni(City,Code) VALUES ("Colombia","Z604");
INSERT INTO codNazioni(City,Code) VALUES ("Ecuador","Z605");
INSERT INTO codNazioni(City,Code) VALUES ("Guyana","Z606");
INSERT INTO codNazioni(City,Code) VALUES ("Paraguay","Z610");
INSERT INTO codNazioni(City,Code) VALUES ("Perù","Z611");
INSERT INTO codNazioni(City,Code) VALUES ("Suriname","Z608");
INSERT INTO codNazioni(City,Code) VALUES ("Trinidad e Tobago","Z612");
INSERT INTO codNazioni(City,Code) VALUES ("Uruguay","Z613");
INSERT INTO codNazioni(City,Code) VALUES ("Venezuela","Z614");
INSERT INTO codNazioni(City,Code) VALUES ("Australia","Z700");
INSERT INTO codNazioni(City,Code) VALUES ("Figi","Z704");
INSERT INTO codNazioni(City,Code) VALUES ("Kiribati","Z731");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Marshall","Z711");
INSERT INTO codNazioni(City,Code) VALUES ("Stati Federati di Micronesia","Z735");
INSERT INTO codNazioni(City,Code) VALUES ("Nauru","Z713");
INSERT INTO codNazioni(City,Code) VALUES ("Nuova Zelanda","Z719");
INSERT INTO codNazioni(City,Code) VALUES ("Palau","Z734");
INSERT INTO codNazioni(City,Code) VALUES ("Papua Nuova Guinea","Z730");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Salomone","Z724");
INSERT INTO codNazioni(City,Code) VALUES ("Samoa","Z726");
INSERT INTO codNazioni(City,Code) VALUES ("Tonga","Z728");
INSERT INTO codNazioni(City,Code) VALUES ("Tuvalu","Z732");
INSERT INTO codNazioni(City,Code) VALUES ("Vanuatu","Z733");
INSERT INTO codNazioni(City,Code) VALUES ("Nuova Caledonia","Z716");
INSERT INTO codNazioni(City,Code) VALUES ("Sahara occidentale","Z339");
INSERT INTO codNazioni(City,Code) VALUES ("Bermuda","Z400");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Cook (NZ)","Z703");
INSERT INTO codNazioni(City,Code) VALUES ("Gibilterra","Z113");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Cayman","Z530");
INSERT INTO codNazioni(City,Code) VALUES ("Anguilla","Z529");
INSERT INTO codNazioni(City,Code) VALUES ("Polinesia francese","Z723");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Fær Øer","Z108");
INSERT INTO codNazioni(City,Code) VALUES ("Aruba","Z501");
INSERT INTO codNazioni(City,Code) VALUES ("Groenlandia","Z402");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Falkland (Malvine)","Z609");
INSERT INTO codNazioni(City,Code) VALUES ("Isola di Man","Z122");
INSERT INTO codNazioni(City,Code) VALUES ("Montserrat","Z531");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Pitcairn","Z722");
INSERT INTO codNazioni(City,Code) VALUES ("Saint Pierre e Miquelon","Z403");
INSERT INTO codNazioni(City,Code) VALUES ("Sant'Elena","Z340");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Turks e Caicos","Z519");
INSERT INTO codNazioni(City,Code) VALUES ("Isole Vergini britanniche","Z525");
INSERT INTO codNazioni(City,Code) VALUES ("Wallis e Futuna","Z729");
