name: Codfiscale CI
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Run SCSS compiler
        run: npm run scss
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm run test
        env:
          HOST: 127.0.0.1
          PORT: 9000
          REDIS_HOST: redis
          REDIS_PORT: 6379
